/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Nguoi_tiep_nhan;
import controller.PhieuNhapModify;
import controller.Phieu_Nhap;
import java.awt.Choice;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class GD_phieu_nhap extends javax.swing.JFrame implements ActionListener{
    DefaultTableModel tableModel;
    List<Phieu_Nhap> phieu_NhapList = new ArrayList<>();
    

    private Phieu_Nhap phieuNhap;
    /**
     * Creates new form GD_phieu_nhap
     * phieu
     */
   
    public GD_phieu_nhap() {
        initComponents();
        showComboData();
        showComboData1();
        tableModel = (DefaultTableModel) tblPhieunhap.getModel();
        setLocationRelativeTo(null);
        btnBack2.addActionListener(this);
        btnDatlai.addActionListener(this);
        btnLuu.addActionListener(this);
        btnXoa.addActionListener(this);
        btnSeach.addActionListener(this);
        phieuNhap = null;
       
        
        showPhieunhap();
      
    }
 
    
    private void showPhieunhap(){
        List<Phieu_Nhap> phieu_NhapList = PhieuNhapModify.findAll();
        
        tableModel.setRowCount(0);
        phieu_NhapList.forEach((phieu_Nhap) -> {
            tableModel.addRow(new Object[] {phieu_Nhap.getNgay(),phieu_Nhap.getDon_vi_quan_li(),phieu_Nhap.getKhu_bep(),phieu_Nhap.getTen_dong_chi_nhan(),phieu_Nhap.getDon_vi_cong_tac(),phieu_Nhap.getKho_nhan_hang(),phieu_Nhap.getTen_vat_tu(),phieu_Nhap.getDon_vi_tinh(),phieu_Nhap.getDon_gia(),phieu_Nhap.getPhai_nhap(),phieu_Nhap.getThuc_nhap()});
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnBack2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtKhubep = new javax.swing.JTextField();
        txtKhonhanhang = new javax.swing.JTextField();
        txtDonvicongtac = new javax.swing.JTextField();
        txtDonviquanli = new javax.swing.JTextField();
        btnLuu = new javax.swing.JButton();
        btnDatlai = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        cbDonvitinh = new javax.swing.JComboBox<>();
        txtPhainhap = new javax.swing.JTextField();
        txtNgay = new javax.swing.JTextField();
        txtThucnhap = new javax.swing.JTextField();
        txtDongia = new javax.swing.JTextField();
        btnSeach = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhieunhap = new javax.swing.JTable();
        cbTen_dong_chi_nhan = new javax.swing.JComboBox<>();
        cbTen_thuc_pham = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\AppData\\Local\\Temp\\icons8_restaurant_on_site_24px_3.png")); // NOI18N
        jLabel1.setText("Phiếu Nhập");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Ngày");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Tên thực phẩm");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Đơn vị quản lí");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Khu bếp");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Kho nhận hàng");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Tên đồng chí nhận");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Đơn vị công tác");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Đơn vị tính");

        btnBack2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack2.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\AppData\\Local\\Temp\\icons8_back_to_30px.png")); // NOI18N
        btnBack2.setText("Trở lại");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Phải nhập");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Thực nhập");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Đơn giá");

        btnLuu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\AppData\\Local\\Temp\\icons8_save_26px_1.png")); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnDatlai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDatlai.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\AppData\\Local\\Temp\\icons8_sync_30px_1.png")); // NOI18N
        btnDatlai.setText("Đặt lại");

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\AppData\\Local\\Temp\\icons8_delete_file_24px.png")); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        cbDonvitinh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbDonvitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kg", "lít", "hộp\t", "bộ" }));
        cbDonvitinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDonvitinhActionPerformed(evt);
            }
        });

        txtNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayActionPerformed(evt);
            }
        });

        btnSeach.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSeach.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\AppData\\Local\\Temp\\icons8_search_26px.png")); // NOI18N
        btnSeach.setText("Tìm kiếm");
        btnSeach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeachActionPerformed(evt);
            }
        });

        tblPhieunhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Ngày", "Đơn vị quản lí", "Khu bếp", "Tên đồng chí nhận", "Đơn vị công tác", "Kho nhận hàng", "Tên thực phẩm", "Đơn vị tính ", "Đơn giá", "Phải nhập", "Thực phập"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPhieunhap);

        cbTen_dong_chi_nhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTen_dong_chi_nhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNgay, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                .addComponent(txtPhainhap))
                            .addComponent(cbTen_dong_chi_nhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTen_thuc_pham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel18))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbDonvitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDonvicongtac, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addComponent(txtThucnhap)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDonviquanli, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(btnDatlai)
                        .addGap(136, 136, 136)
                        .addComponent(btnXoa)
                        .addGap(189, 189, 189)
                        .addComponent(btnSeach)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 78, Short.MAX_VALUE)
                                .addComponent(btnLuu)
                                .addGap(180, 180, 180))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtKhubep, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                                    .addComponent(txtKhonhanhang)
                                    .addComponent(txtDongia))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack2)
                        .addGap(23, 23, 23))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtDonviquanli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtKhubep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cbTen_dong_chi_nhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtDonvicongtac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtKhonhanhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(cbDonvitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15)
                                .addComponent(jLabel19))
                            .addComponent(cbTen_thuc_pham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtPhainhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(txtThucnhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtDongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuu)
                    .addComponent(btnSeach)
                    .addComponent(btnXoa)
                    .addComponent(btnDatlai, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayActionPerformed

    private void btnSeachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeachActionPerformed

    private void cbDonvitinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDonvitinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDonvitinhActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btnLuuActionPerformed

    private void cbTen_dong_chi_nhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTen_dong_chi_nhanActionPerformed
        // TODO add your handling code here:
        String selectedItem = (String) cbTen_dong_chi_nhan.getSelectedItem();
    }//GEN-LAST:event_cbTen_dong_chi_nhanActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa thông tin không", "Hỏi", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.NO_OPTION){return;}
        
        for (Phieu_Nhap phieu_Nhap : phieu_NhapList) {
            if(phieu_Nhap.getNgay().equals(txtNgay.getText()))
                phieu_NhapList.remove(phieu_Nhap);
                break;
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
   
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GD_phieu_nhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GD_phieu_nhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GD_phieu_nhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GD_phieu_nhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GD_phieu_nhap().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnDatlai;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSeach;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbDonvitinh;
    private javax.swing.JComboBox<String> cbTen_dong_chi_nhan;
    private javax.swing.JComboBox<String> cbTen_thuc_pham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tblPhieunhap;
    private javax.swing.JTextField txtDongia;
    private javax.swing.JTextField txtDonvicongtac;
    private javax.swing.JTextField txtDonviquanli;
    private javax.swing.JTextField txtKhonhanhang;
    private javax.swing.JTextField txtKhubep;
    private javax.swing.JTextField txtNgay;
    private javax.swing.JTextField txtPhainhap;
    private javax.swing.JTextField txtThucnhap;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
       if(e.getSource().equals(btnLuu))
       {
           btn_LuuClick();
       }
       else {
           if(e.getSource().equals(btnDatlai))
           {
           btn_DatlaiClick();
           }
           else {
               if(e.getSource().equals(btnXoa))
               {
               btn_XoaClick();}
               else {
                   if(e.getSource().equals(btnSeach))
           {
           btn_SeachClick();
           }
                   else
               btn_Back2Click();
               }
           }   
       }
    }
       public void btn_LuuClick(){
             StringBuilder sb = new StringBuilder();
        if(txtNgay.getText().equals("")){
        sb.append("Ngày không được để trống \n");
        txtNgay.setBackground(Color.red);
        } else {txtNgay.setBackground(Color.white);}
         if(txtDonviquanli.getText().equals("")){
        sb.append("Đơn vị quản lí không được để trống \n");
        txtDonviquanli.setBackground(Color.red);
        } else {txtDonviquanli.setBackground(Color.white);}
          if(txtKhubep.getText().equals("")){
        sb.append("Khu bếp không được để trống \n");
        txtKhubep.setBackground(Color.red);
        }else {txtKhubep.setBackground(Color.white);}
           if(txtKhonhanhang.getText().equals("")){
        sb.append("Kho nhận hàng không được để trống \n");
        txtKhonhanhang.setBackground(Color.red);
        }else {txtKhonhanhang.setBackground(Color.white);}
            if(cbTen_dong_chi_nhan.getSelectedItem().toString().equals("")){
        sb.append("Tên đồng chí nhận không được để trống \n");
        cbTen_dong_chi_nhan.setBackground(Color.red);
        }else {cbTen_dong_chi_nhan.setBackground(Color.white);}
                if(txtDonvicongtac.getText().equals("")){
        sb.append("Đơn giá không được để trống \n");
        txtDonvicongtac.setBackground(Color.red);
        }else {txtDonvicongtac.setBackground(Color.white);}
             if(cbTen_thuc_pham.getSelectedItem().toString().equals("")){
        sb.append("Tên vật tư không được để trống \n");
        cbTen_thuc_pham.setBackground(Color.red);
        }else {cbTen_thuc_pham.setBackground(Color.white);}
              if(txtDongia.getText().equals("")){
        sb.append("Đơn giá không được để trống \n");
        txtDongia.setBackground(Color.red);
        }else {txtDongia.setBackground(Color.white);}
                  if(txtPhainhap.getText().equals("")){
        sb.append("Đơn giá không được để trống \n");
        txtPhainhap.setBackground(Color.red);
        }else {txtPhainhap.setBackground(Color.white);}
                      if(txtThucnhap.getText().equals("")){
        sb.append("Đơn giá không được để trống \n");
        txtThucnhap.setBackground(Color.red);
        }else {txtThucnhap.setBackground(Color.white);}
              if(sb.length()>0){
                  JOptionPane.showMessageDialog(this, sb.toString(),"Errror",JOptionPane.ERROR_MESSAGE);
              }
              Phieu_Nhap pn = new Phieu_Nhap();
              pn.setNgay(txtNgay.getText());
              pn.setDon_vi_quan_li(txtDonviquanli.getText());
              pn.setKho_nhan_hang(txtKhonhanhang.getText());
              pn.setKhu_bep(txtKhubep.getText());
              pn.setTen_dong_chi_nhan(cbTen_dong_chi_nhan.getSelectedItem().toString());
              pn.setDon_vi_cong_tac(txtDonvicongtac.getText());
              pn.setTen_vat_tu(cbTen_thuc_pham.getSelectedItem().toString());
              pn.setDon_vi_tinh(cbDonvitinh.getSelectedItem().toString());
                
              pn.setPhai_nhap(Float.parseFloat(txtPhainhap.getText()));
              pn.setThuc_nhap(Float.parseFloat(txtThucnhap.getText()));
              pn.setDon_gia(Integer.parseInt(txtDongia.getText()));
              tableModel.addRow(new Object[]{pn.getNgay(),pn.getDon_vi_quan_li(),pn.getKhu_bep(),pn.getTen_dong_chi_nhan(),pn.getDon_vi_cong_tac(),pn.getDon_vi_cong_tac(),pn.getTen_vat_tu(),pn.getDon_vi_tinh(),pn.getDon_gia(),pn.getPhai_nhap(),pn.getThuc_nhap()});
              phieu_NhapList.add(pn);
              
              
       }
       public void btn_DatlaiClick(){
           txtDongia.setText("");
           txtDonvicongtac.setText("");
           txtDonviquanli.setText("");
           txtKhonhanhang.setText("");
           txtKhubep.setText("");
           txtNgay.setText("");
           txtPhainhap.setText("");
           cbTen_dong_chi_nhan.setSelectedIndex(0);
           cbTen_thuc_pham.setSelectedIndex(0);
           txtThucnhap.setText("");
           cbDonvitinh.setSelectedIndex(0);
         
           
       }
       public void btn_XoaClick(){
       
       }
       public void btn_Back2Click(){
           new GD_QL_Kho().setVisible(true);
        this.dispose();
       }
       public void btn_SeachClick(){
       
       }

    private void showComboData() {
        List<Nguoi_tiep_nhan> ntnList = PhieuNhapModify.Ten_dong_chi_nhan();
        for (Nguoi_tiep_nhan nguoi_tiep_nhan : ntnList) {
            cbTen_dong_chi_nhan.addItem(nguoi_tiep_nhan.getTen_dong_chi_nhan().toString());
            
        }
        
    }

    private void showComboData1() {
    List<Phieu_Nhap> pnList = PhieuNhapModify.findAll();
        for (Phieu_Nhap phieu_Nhap : pnList) {
            cbTen_thuc_pham.addItem(phieu_Nhap.getTen_vat_tu().toString());
            
        }
    
    }
     
}

